<?xml version="1.0" encoding="utf-8"?><Database Name="SPRHR_Solution" Class="SPRHR_SolutionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-F32KOUU\SQLEXPRESS;Initial Catalog=SPRHR_Solution;Integrated Security=True" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="SPRHR_SolutionConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BangGiaBan" Member="BangGiaBans">
    <Type Name="BangGiaBan">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="giaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ngayApDung" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="BangGiaBan_ChiTietHoaDonBanHang" Member="ChiTietHoaDonBanHangs" ThisKey="maSP" OtherKey="maSP" Type="ChiTietHoaDonBanHang" />
      <Association Name="BangGiaBan_SanPham" Member="SanPham" ThisKey="maSP" OtherKey="MaSP" Type="SanPham" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinKho" Member="ThongTinKhos">
    <Type Name="ThongTinKho">
      <Column Name="maKho" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="soDienThoai" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="ThongTinKho_ChiTietKho" Member="ChiTietKhos" ThisKey="maKho" OtherKey="maKho" Type="ChiTietKho" />
      <Association Name="ThongTinKho_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="maKho" OtherKey="makho" Type="PhieuNhapKho" />
      <Association Name="ThongTinKho_PhieuXuatKho" Member="PhieuXuatKhos" ThisKey="maKho" OtherKey="makho" Type="PhieuXuatKho" />
      <Association Name="ThongTinKho_QuanLyKho" Member="QuanLyKhos" ThisKey="maKho" OtherKey="maKho" Type="QuanLyKho" />
    </Type>
  </Table>
  <Table Name="dbo.BangGiaBanSi" Member="BangGiaBanSis">
    <Type Name="BangGiaBanSi">
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="giaBan" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="BangGiaBanSi_ChiTietHoaDonBanSi" Member="ChiTietHoaDonBanSis" ThisKey="maSP" OtherKey="MaSP" Type="ChiTietHoaDonBanSi" />
      <Association Name="SanPham_BangGiaBanSi" Member="SanPham" ThisKey="maSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonBanHang" Member="ChiTietHoaDonBanHangs">
    <Type Name="ChiTietHoaDonBanHang">
      <Column Name="soHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soCTHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="giaKhuyenMai" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="BangGiaBan_ChiTietHoaDonBanHang" Member="BangGiaBan" ThisKey="maSP" OtherKey="maSP" Type="BangGiaBan" IsForeignKey="true" />
      <Association Name="HoaDonBanHang_ChiTietHoaDonBanHang" Member="HoaDonBanHang" ThisKey="soHD" OtherKey="soHD" Type="HoaDonBanHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonBanSi" Member="ChiTietHoaDonBanSis">
    <Type Name="ChiTietHoaDonBanSi">
      <Column Name="MaHoaDonBanSi" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBanSi" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="BangGiaBanSi_ChiTietHoaDonBanSi" Member="BangGiaBanSi" ThisKey="MaSP" OtherKey="maSP" Type="BangGiaBanSi" IsForeignKey="true" />
      <Association Name="HoaDonBanSi_ChiTietHoaDonBanSi" Member="HoaDonBanSi" ThisKey="MaHoaDonBanSi" OtherKey="MaHoaDonBanSi" Type="HoaDonBanSi" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietHoaDonBanSi" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonNhaCungCap" Member="ChiTietHoaDonNhaCungCaps">
    <Type Name="ChiTietHoaDonNhaCungCap">
      <Column Name="MaHoaDonNhaCungCap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSPNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaMuaBenNhaCungCap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="HoaDonNhaCungCap_ChiTietHoaDonNhaCungCap" Member="HoaDonNhaCungCap" ThisKey="MaHoaDonNhaCungCap" OtherKey="MaHoaDonNCC" Type="HoaDonNhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietKho" Member="ChiTietKhos">
    <Type Name="ChiTietKho">
      <Column Name="maKho" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ThongTinKho_ChiTietKho" Member="ThongTinKho" ThisKey="maKho" OtherKey="maKho" Type="ThongTinKho" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietKho" Member="SanPham" ThisKey="maSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietKhuyenMai" Member="ChiTietKhuyenMais">
    <Type Name="ChiTietKhuyenMai">
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaChiTietKhuyenMai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MucGiam" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GiaKhuyenMai" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="ChuongTrinhKhuyenMai_ChiTietKhuyenMai" Member="ChuongTrinhKhuyenMai" ThisKey="MaCT" OtherKey="MaCT" Type="ChuongTrinhKhuyenMai" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietKhuyenMai" Member="SanPham" ThisKey="MaSp" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietKyLuat" Member="ChiTietKyLuats">
    <Type Name="ChiTietKyLuat">
      <Column Name="maKyLuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLapKyLuat" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lyDo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ngayApDungKyLuat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetThucKyLuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KyLuat_ChiTietKyLuat" Member="KyLuat" ThisKey="maKyLuat" OtherKey="maKyLuat" Type="KyLuat" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTietKyLuat" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietLich" Member="ChiTietLiches">
    <Type Name="ChiTietLich">
      <Column Name="maLich" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LichLamViec_ChiTietLich" Member="LichLamViec" ThisKey="maLich" OtherKey="maLich" Type="LichLamViec" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTietLich" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuDNNK" Member="ChiTietPhieuDNNKs">
    <Type Name="ChiTietPhieuDNNK">
      <Column Name="MaPhieuDNNK" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PhieuDNNK_ChiTietPhieuDNNK" Member="PhieuDNNK" ThisKey="MaPhieuDNNK" OtherKey="MaPhieuDNNK" Type="PhieuDNNK" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieuDNNK" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuDNXK" Member="ChiTietPhieuDNXKs">
    <Type Name="ChiTietPhieuDNXK">
      <Column Name="MaPhieuDNXK" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PhieuDNXK_ChiTietPhieuDNXK" Member="PhieuDNXK" ThisKey="MaPhieuDNXK" OtherKey="MaPhieuDNXK" Type="PhieuDNXK" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieuDNXK" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChitietPhieuTranoKH" Member="ChitietPhieuTranoKHs">
    <Type Name="ChitietPhieuTranoKH">
      <Column Name="sophieuTrano" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masoCNKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sotien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CongnoKH_ChitietPhieuTranoKH" Member="CongnoKH" ThisKey="masoCNKH" OtherKey="masoCNKH" Type="CongnoKH" IsForeignKey="true" />
      <Association Name="PhieuTranoKH_ChitietPhieuTranoKH" Member="PhieuTranoKH" ThisKey="sophieuTrano" OtherKey="sophieuTN" Type="PhieuTranoKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChitietTranoNCC" Member="ChitietTranoNCCs">
    <Type Name="ChitietTranoNCC">
      <Column Name="sophieuTN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masoCNNCC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sotien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CongNoNCC_ChitietTranoNCC" Member="CongNoNCC" ThisKey="masoCNNCC" OtherKey="masoCNNCC" Type="CongNoNCC" IsForeignKey="true" />
      <Association Name="PhieuTranoNCC_ChitietTranoNCC" Member="PhieuTranoNCC" ThisKey="sophieuTN" OtherKey="sophieuTN" Type="PhieuTranoNCC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="maChucVu" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenChucVU" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ChucVu_LichSuLamViec" Member="LichSuLamViecs" ThisKey="maChucVu" OtherKey="maChucVu" Type="LichSuLamViec" />
    </Type>
  </Table>
  <Table Name="dbo.ChuongTrinhDaoTao" Member="ChuongTrinhDaoTaos">
    <Type Name="ChuongTrinhDaoTao">
      <Column Name="machuongTrinhDaoTao" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenChuongTrinhDaoTao" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="coSoDaoTao" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ChuongTrinhDaoTao_QuaTrinhDaoTao" Member="QuaTrinhDaoTaos" ThisKey="machuongTrinhDaoTao" OtherKey="maChuongTrinhDaoTao" Type="QuaTrinhDaoTao" />
    </Type>
  </Table>
  <Table Name="dbo.ChuongTrinhKhuyenMai" Member="ChuongTrinhKhuyenMais">
    <Type Name="ChuongTrinhKhuyenMai">
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayKhoiDong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ChuongTrinhKhuyenMai_ChiTietKhuyenMai" Member="ChiTietKhuyenMais" ThisKey="MaCT" OtherKey="MaCT" Type="ChiTietKhuyenMai" />
    </Type>
  </Table>
  <Table Name="dbo.CongnoKH" Member="CongnoKHs">
    <Type Name="CongnoKH">
      <Column Name="masoCNKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soHDBS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sotienNo" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayDaoHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CongnoKH_ChitietPhieuTranoKH" Member="ChitietPhieuTranoKHs" ThisKey="masoCNKH" OtherKey="masoCNKH" Type="ChitietPhieuTranoKH" />
      <Association Name="HoaDonBanSi_CongnoKH" Member="HoaDonBanSi" ThisKey="soHDBS" OtherKey="MaHoaDonBanSi" Type="HoaDonBanSi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CongNoNCC" Member="CongNoNCCs">
    <Type Name="CongNoNCC">
      <Column Name="masoCNNCC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soHDNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sotienNo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayDaoHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CongNoNCC_ChitietTranoNCC" Member="ChitietTranoNCCs" ThisKey="masoCNNCC" OtherKey="masoCNNCC" Type="ChitietTranoNCC" />
      <Association Name="HoaDonNhaCungCap_CongNoNCC" Member="HoaDonNhaCungCap" ThisKey="soHDNCC" OtherKey="MaHoaDonNCC" Type="HoaDonNhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhGia" Member="DanhGias">
    <Type Name="DanhGia">
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayDanhGia" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="loaiDanhGia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NhanVien_DanhGia" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucCuaHang" Member="DanhMucCuaHangs">
    <Type Name="DanhMucCuaHang">
      <Column Name="MaCuaHang" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCuaHang" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucCuaHang_PhieuDNXK" Member="PhieuDNXKs" ThisKey="MaCuaHang" OtherKey="MaCuaHang" Type="PhieuDNXK" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBanHang" Member="HoaDonBanHangs">
    <Type Name="HoaDonBanHang">
      <Column Name="soHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HoaDonBanHang_ChiTietHoaDonBanHang" Member="ChiTietHoaDonBanHangs" ThisKey="soHD" OtherKey="soHD" Type="ChiTietHoaDonBanHang" />
      <Association Name="HoaDonBanHang_ThanhToan" Member="ThanhToans" ThisKey="soHD" OtherKey="soHD" Type="ThanhToan" />
      <Association Name="KhachHang_HoaDonBanHang" Member="KhachHang" ThisKey="maKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDonBanHang" Member="NhanVien" ThisKey="maNV" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBanSi" Member="HoaDonBanSis">
    <Type Name="HoaDonBanSi">
      <Column Name="MaHoaDonBanSi" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="soTienDatra" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HoaDonBanSi_ChiTietHoaDonBanSi" Member="ChiTietHoaDonBanSis" ThisKey="MaHoaDonBanSi" OtherKey="MaHoaDonBanSi" Type="ChiTietHoaDonBanSi" />
      <Association Name="HoaDonBanSi_CongnoKH" Member="CongnoKHs" ThisKey="MaHoaDonBanSi" OtherKey="soHDBS" Type="CongnoKH" />
      <Association Name="HoaDonBanSi_PhieuDNXK" Member="PhieuDNXKs" ThisKey="MaHoaDonBanSi" OtherKey="MaHoaDonBanSi" Type="PhieuDNXK" />
      <Association Name="KhachHang_HoaDonBanSi" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonNhaCungCap" Member="HoaDonNhaCungCaps">
    <Type Name="HoaDonNhaCungCap">
      <Column Name="MaHoaDonNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhaCungCap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="sotienDatra" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HoaDonNhaCungCap_ChiTietHoaDonNhaCungCap" Member="ChiTietHoaDonNhaCungCaps" ThisKey="MaHoaDonNCC" OtherKey="MaHoaDonNhaCungCap" Type="ChiTietHoaDonNhaCungCap" />
      <Association Name="HoaDonNhaCungCap_CongNoNCC" Member="CongNoNCCs" ThisKey="MaHoaDonNCC" OtherKey="soHDNCC" Type="CongNoNCC" />
      <Association Name="HoaDonNhaCungCap_PhieuDNNK" Member="PhieuDNNKs" ThisKey="MaHoaDonNCC" OtherKey="MaHoaDonNCC" Type="PhieuDNNK" />
      <Association Name="NhaCungCap_HoaDonNhaCungCap" Member="NhaCungCap" ThisKey="MaNhaCungCap" OtherKey="MaNhaCungCap" Type="NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTKH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaSoThue" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TenCongTy" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChiCongTy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SDTCongTy" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EmailCongTy" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SoTaiKhoanNH" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TenNH" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ChiNhanhNH" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="MaKH" OtherKey="maKH" Type="HoaDonBanHang" />
      <Association Name="KhachHang_HoaDonBanSi" Member="HoaDonBanSis" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDonBanSi" />
      <Association Name="KhachHang_PhieuTranoKH" Member="PhieuTranoKHs" ThisKey="MaKH" OtherKey="MaKH" Type="PhieuTranoKH" />
      <Association Name="KhachHang_TheThanhVien" Member="TheThanhViens" ThisKey="MaKH" OtherKey="MaKH" Type="TheThanhVien" />
    </Type>
  </Table>
  <Table Name="dbo.KyLuat" Member="KyLuats">
    <Type Name="KyLuat">
      <Column Name="maKyLuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dieuKhoanKyLuat" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="hinhThucKyLuat" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="KyLuat_ChiTietKyLuat" Member="ChiTietKyLuats" ThisKey="maKyLuat" OtherKey="maKyLuat" Type="ChiTietKyLuat" />
    </Type>
  </Table>
  <Table Name="dbo.LichLamViec" Member="LichLamViecs">
    <Type Name="LichLamViec">
      <Column Name="maLich" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="caLamViec" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gioLam" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="gioKetThuc" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LichLamViec_ChiTietLich" Member="ChiTietLiches" ThisKey="maLich" OtherKey="maLich" Type="ChiTietLich" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuLamViec" Member="LichSuLamViecs">
    <Type Name="LichSuLamViec">
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPhongBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayBatDauLamViec" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maChucVu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ChucVu_LichSuLamViec" Member="ChucVu" ThisKey="maChucVu" OtherKey="maChucVu" Type="ChucVu" IsForeignKey="true" />
      <Association Name="NhanVien_LichSuLamViec" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhongBan_LichSuLamViec" Member="PhongBan" ThisKey="maPhongBan" OtherKey="maPhongBan" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="MaLoaiSanPham" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNhaCungCap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhaCungCap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThanhLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NhaCungCap_HoaDonNhaCungCap" Member="HoaDonNhaCungCaps" ThisKey="MaNhaCungCap" OtherKey="MaNhaCungCap" Type="HoaDonNhaCungCap" />
      <Association Name="NhaCungCap_PhieuTranoNCC" Member="PhieuTranoNCCs" ThisKey="MaNhaCungCap" OtherKey="MasoNCC" Type="PhieuTranoNCC" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoTenNhanVien" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDauLamViec" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="soTKNganHang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="queQuan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ChiTietKyLuat" Member="ChiTietKyLuats" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="ChiTietKyLuat" />
      <Association Name="NhanVien_ChiTietLich" Member="ChiTietLiches" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="ChiTietLich" />
      <Association Name="NhanVien_DanhGia" Member="DanhGias" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="DanhGia" />
      <Association Name="NhanVien_HoaDonBanHang" Member="HoaDonBanHangs" ThisKey="maNhanVien" OtherKey="maNV" Type="HoaDonBanHang" />
      <Association Name="NhanVien_LichSuLamViec" Member="LichSuLamViecs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="LichSuLamViec" />
      <Association Name="NhanVien_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="maNhanVien" OtherKey="manhanvien" Type="PhieuNhapKho" />
      <Association Name="NhanVien_PhieuTranoKH" Member="PhieuTranoKHs" ThisKey="maNhanVien" OtherKey="msNhanVien" Type="PhieuTranoKH" />
      <Association Name="NhanVien_PhieuTranoNCC" Member="PhieuTranoNCCs" ThisKey="maNhanVien" OtherKey="msNhanVien" Type="PhieuTranoNCC" />
      <Association Name="NhanVien_PhieuXuatKho" Member="PhieuXuatKhos" ThisKey="maNhanVien" OtherKey="manhanvien" Type="PhieuXuatKho" />
      <Association Name="NhanVien_QuanLyKho" Member="QuanLyKhos" ThisKey="maNhanVien" OtherKey="manhanvien" Type="QuanLyKho" />
      <Association Name="NhanVien_QuaTrinhDaoTao" Member="QuaTrinhDaoTaos" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="QuaTrinhDaoTao" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDNNK" Member="PhieuDNNKs">
    <Type Name="PhieuDNNK">
      <Column Name="MaPhieuDNNK" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaKho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tinhtrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHoaDonNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDNNK_ChiTietPhieuDNNK" Member="ChiTietPhieuDNNKs" ThisKey="MaPhieuDNNK" OtherKey="MaPhieuDNNK" Type="ChiTietPhieuDNNK" />
      <Association Name="HoaDonNhaCungCap_PhieuDNNK" Member="HoaDonNhaCungCap" ThisKey="MaHoaDonNCC" OtherKey="MaHoaDonNCC" Type="HoaDonNhaCungCap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDNXK" Member="PhieuDNXKs">
    <Type Name="PhieuDNXK">
      <Column Name="MaPhieuDNXK" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaKho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tinhtrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHoaDonBanSi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaCuaHang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PhieuDNXK_ChiTietPhieuDNXK" Member="ChiTietPhieuDNXKs" ThisKey="MaPhieuDNXK" OtherKey="MaPhieuDNXK" Type="ChiTietPhieuDNXK" />
      <Association Name="PhieuDNXK_PhieuXuatKho" Member="PhieuXuatKho" ThisKey="MaPhieuDNXK" OtherKey="soPXK" Type="PhieuXuatKho" Cardinality="One" />
      <Association Name="DanhMucCuaHang_PhieuDNXK" Member="DanhMucCuaHang" ThisKey="MaCuaHang" OtherKey="MaCuaHang" Type="DanhMucCuaHang" IsForeignKey="true" />
      <Association Name="HoaDonBanSi_PhieuDNXK" Member="HoaDonBanSi" ThisKey="MaHoaDonBanSi" OtherKey="MaHoaDonBanSi" Type="HoaDonBanSi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapKho" Member="PhieuNhapKhos">
    <Type Name="PhieuNhapKho">
      <Column Name="sopnk" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="manhanvien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="makho" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhieuNhapKho" Member="NhanVien" ThisKey="manhanvien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="ThongTinKho_PhieuNhapKho" Member="ThongTinKho" ThisKey="makho" OtherKey="maKho" Type="ThongTinKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTranoKH" Member="PhieuTranoKHs">
    <Type Name="PhieuTranoKH">
      <Column Name="sophieuTN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="msNhanVien" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="PhieuTranoKH_ChitietPhieuTranoKH" Member="ChitietPhieuTranoKHs" ThisKey="sophieuTN" OtherKey="sophieuTrano" Type="ChitietPhieuTranoKH" />
      <Association Name="KhachHang_PhieuTranoKH" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuTranoKH" Member="NhanVien" ThisKey="msNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuTranoNCC" Member="PhieuTranoNCCs">
    <Type Name="PhieuTranoNCC">
      <Column Name="sophieuTN" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MasoNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="msNhanVien" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="PhieuTranoNCC_ChitietTranoNCC" Member="ChitietTranoNCCs" ThisKey="sophieuTN" OtherKey="sophieuTN" Type="ChitietTranoNCC" />
      <Association Name="NhaCungCap_PhieuTranoNCC" Member="NhaCungCap" ThisKey="MasoNCC" OtherKey="MaNhaCungCap" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuTranoNCC" Member="NhanVien" ThisKey="msNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuatKho" Member="PhieuXuatKhos">
    <Type Name="PhieuXuatKho">
      <Column Name="soPXK" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="manhanvien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="makho" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="NhanVien_PhieuXuatKho" Member="NhanVien" ThisKey="manhanvien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhieuDNXK_PhieuXuatKho" Member="PhieuDNXK" ThisKey="soPXK" OtherKey="MaPhieuDNXK" Type="PhieuDNXK" IsForeignKey="true" />
      <Association Name="ThongTinKho_PhieuXuatKho" Member="ThongTinKho" ThisKey="makho" OtherKey="maKho" Type="ThongTinKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="maPhongBan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenPhongBan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="khuVuc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="PhongBan_LichSuLamViec" Member="LichSuLamViecs" ThisKey="maPhongBan" OtherKey="maPhongBan" Type="LichSuLamViec" />
    </Type>
  </Table>
  <Table Name="dbo.PhuongThucThanhToan" Member="PhuongThucThanhToans">
    <Type Name="PhuongThucThanhToan">
      <Column Name="maPhuongThuc" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenPhuongThuc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PhuongThucThanhToan_ThanhToan" Member="ThanhToans" ThisKey="maPhuongThuc" OtherKey="maPhuongThuc" Type="ThanhToan" />
    </Type>
  </Table>
  <Table Name="dbo.QuanLyKho" Member="QuanLyKhos">
    <Type Name="QuanLyKho">
      <Column Name="maKho" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="manhanvien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chucVu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="thoiGianBatDau" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thoiGianKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_QuanLyKho" Member="NhanVien" ThisKey="manhanvien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="ThongTinKho_QuanLyKho" Member="ThongTinKho" ThisKey="maKho" OtherKey="maKho" Type="ThongTinKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuaTrinhDaoTao" Member="QuaTrinhDaoTaos">
    <Type Name="QuaTrinhDaoTao">
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maChuongTrinhDaoTao" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayDuocDaoTao" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayKetThucDaoTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="loaiDanhGia" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ChuongTrinhDaoTao_QuaTrinhDaoTao" Member="ChuongTrinhDaoTao" ThisKey="maChuongTrinhDaoTao" OtherKey="machuongTrinhDaoTao" Type="ChuongTrinhDaoTao" IsForeignKey="true" />
      <Association Name="NhanVien_QuaTrinhDaoTao" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySanXuat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="KieuDang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MauSac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrongLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaLoaiSanPham" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_BangGiaBanSi" Member="BangGiaBanSi" ThisKey="MaSP" OtherKey="maSP" Type="BangGiaBanSi" Cardinality="One" />
      <Association Name="SanPham_ChiTietHoaDonBanSi" Member="ChiTietHoaDonBanSis" ThisKey="MaSP" OtherKey="MaSP" Type="ChiTietHoaDonBanSi" />
      <Association Name="SanPham_ChiTietKho" Member="ChiTietKhos" ThisKey="MaSP" OtherKey="maSP" Type="ChiTietKho" />
      <Association Name="SanPham_ChiTietKhuyenMai" Member="ChiTietKhuyenMais" ThisKey="MaSP" OtherKey="MaSp" Type="ChiTietKhuyenMai" />
      <Association Name="SanPham_ChiTietPhieuDNNK" Member="ChiTietPhieuDNNKs" ThisKey="MaSP" OtherKey="MaSP" Type="ChiTietPhieuDNNK" />
      <Association Name="SanPham_ChiTietPhieuDNXK" Member="ChiTietPhieuDNXKs" ThisKey="MaSP" OtherKey="MaSP" Type="ChiTietPhieuDNXK" />
      <Association Name="BangGiaBan_SanPham" Member="BangGiaBan" ThisKey="MaSP" OtherKey="maSP" Type="BangGiaBan" IsForeignKey="true" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="LoaiSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="soHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="maPhuongThuc" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HoaDonBanHang_ThanhToan" Member="HoaDonBanHang" ThisKey="soHD" OtherKey="soHD" Type="HoaDonBanHang" IsForeignKey="true" />
      <Association Name="PhuongThucThanhToan_ThanhToan" Member="PhuongThucThanhToan" ThisKey="maPhuongThuc" OtherKey="maPhuongThuc" Type="PhuongThucThanhToan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheThanhVien" Member="TheThanhViens">
    <Type Name="TheThanhVien">
      <Column Name="MaThe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayCapThe" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SoDiem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_TheThanhVien" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
</Database>